### ISSUE TITLE
Does not exist as error in npm script

### ISSUE THREAD

**Issue by betimer** [revathskumar/npm-audit-ci#5] opened 2018-12-07 03:06 UTC
npm: 6.4.1
npm script: `npm-audit-ci --critical && npm run build`

I tested that even though there is a critical package, the npm run build still runs, which means the `npm-audit-ci --critical` does not fail

**Comment by wilgert** [comment] 2018-12-10 17:20
It is because the output of `npm audit` has changed. I have created a Pull request: #6  But somehow the build fails with node 10. Trying to fix that.

**Comment by revathskumar** [comment] 2018-12-29 19:06
@betimer I have merged @wilgert's PR and did a new release. Can you check and update if the issue is resolved.

Thanks.
Please reopen if the issue is still there.

**Closed by revathskumar** 2018-12-29 19:06 UTC
